---
title: "SRT411-A0"
author: "LorraineDyer"
date: "February 13, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```Acknowledged Sources
R Markdown cheat sheet - https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf
ggplot 2 - http://statmodeling.com/best-way-to-add-a-footnote-to-a-plot-created-with-ggplot2.html
My_knitr.Rmd - by Mike Martin
A (very) short introduction to R document
```

```The username created for this github account is ldyer1.
This assignment entails a series of R Programming exercises which include mathematical calculations, matrices, plots and sequences.
```

```3.1 Calculator
Compute the difference between 2014 and the year you started at university and divide this by the difference between 2014 and the year you were born. Multiply this with 100 to get the percentage of your life spent at university.
((2014-2014)/(2014-1992)) * 100
```

```{r}
((2014-2014)/(2011-1992)) * 100
```


```3.1 Workspace
Repeat previous example but with several steps in between.
grad = 2018
entranceyr = 2013
birth_year = 1992
x <- grad - entranceyr /entranceyr - birth_year
```
```{r}
grad = 2018
entranceyr = 2013
birth_year = 1992
x <- grad - entranceyr /entranceyr - birth_year
x
```

```
3.4 Functions
Compute the sum of 4,5,8, and 11
y <- c(4,5,8,11)
sum(y)
```

```{r} 
y <- c(4,5,8,11)
sum(y)
```

```3.5 Plots
Plot 100 normal random numbers
a = rnorm(100)
plot(a)
```
```{r}
a = rnorm(100)
plot(a)
```

```4 Help and Documentation
Find help for the sqrt function
help(sqrt)
```
```{r}
help(sqrt)
```

```5 Scripts
Make a file called 'firstscript.R' containing R-Code that generates 100 random numbers and plots them and run this script several times.
x <-rnorm(100)
plot (h)
source("firstscript.R")
```
```{r}
h <-rnorm(100)
plot (h)
```

```6.2 Matrices
Put the numbers 31 to 60 in a vector named P and in a matrix with 6 rows and 5 columns named Q. Tip: use the function seq. Look at the different ways scalars, vectors and matrices are denoted in the workspace window.
P <- c(31:60) 
mat=matrix(data=P,ncol=5,nrow=6) 
mat
```
```{r}
P <- c(31:60)
mat <- matrix(data=P,ncol=5,nrow=6)
mat
```

```6.3 Data Frames
Make a script file which constructs three random
normal vectors of length 100. Call these
vectors x1, x2 and x3. Make a data frame called
t with three columns (called a, b and c) containing
respectively x1, x1+x2 and x1+x2+x3.
Call the following functions for this data frame:
  plot(t) and sd(t). Can you understand the
results? Rerun this script a few times.
```
```{r}
x1 <- c(100)
x2 <- c(100)
x3 <- c(100)

a <- x1
b <- x1 + x2
c <- x1 + x2 + x3
u <- data.frame(a,b,c)
h

plot(h)

sd(h)
```
```
#8. Reading and writing data files
d = data.frame(a = c(3,4,5))
b = c(12,43,54)
write.table(d, file="tst1.txt", row.names=FALSE)
d2 = read.table(file="tst1.txt", header=TRUE)
d2
d = data.frame(a = c(3,4,5))
b = c(12,43,54)
write.table(d, file="tst1.txt", row.names=FALSE)
d2 = read.table(file="tst1.txt", header=TRUE)
d2
```
```
#9. Not available data
Compute the mean of the square root of a vector of 100 random numbers.
a <-sqrt(rnorm(100)
a
```
```{r}
a <-sqrt(rnorm(100))
a
```

```
10.2 Dates
Make a graph with on the x-axis: today, Sinterklaas
2014 and your next birthday and on the y-axis the number of presents you expect on 
each of these days.
date1=strptime( c("20170131","20141225", "20170511"),format="%Y%m%d")
presents <- c(0,1,1)
datevspresents <- plot(x = date1, y = presents)
datevspresents
```
```{r}
date1=strptime( c("20170131","20141225", "20170511"),format="%Y%m%d")
presents <- c(0,1,1)
datevspresents <- plot(x = date1, y = presents)
datevspresents
```
```
#11.2 For-Loop
####Make a vector from 1 to 100. Make a for-loop ####which runs through the whole vector. Multiply ####the elements which are smaller than 5 and larger ####than 90 with 10 and the other elements with 0.1.
####```{r, echo=FALSE} ####j = seq( from=1, to=100) ####s= c() ####for (i in 1:100)
{
  s[i] < 5 = j[i] > 90 * 10
}
```
```
####s ####```
#The final Todo in the document has a footnote. Write code that will prove that footnote true
####l <- annotate("info", label = "Footnote", colour = black) ####l
```


